# Generated by Django 5.1.3 on 2026-07-02 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='mesa',
            field=models.PositiveIntegerField(default=1, help_text='Número de mesa atendida.'),
        ),
    ]
