# Generated by Django 5.1.3 on 2026-07-02 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_venta_mesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='tipo',
            field=models.CharField(choices=[('mesa', 'Mesa'), ('llevar', 'Para llevar')], default='mesa', help_text='Mesa (se atiende en el local) o Para llevar.', max_length=10),
        ),
        migrations.AlterField(
            model_name='venta',
            name='mesa',
            field=models.PositiveIntegerField(blank=True, help_text='Número de mesa (solo si tipo=mesa).', null=True),
        ),
    ]
